name: build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: [5.0.x]

    steps:
      - uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # renovate: tag=v2.4.0

      - name: Setup .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@499789684c9a0d41c9b3f0d66a785ba17b1d51ab # renovate: tag=v1.9.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: prepare macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install mono-libgdiplus

      - name: restore packages
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: test
        run: dotnet run --no-build

      - uses: actions/upload-artifact@27121b0bdffd731efa15d66772be8dc71245d074 # renovate: tag=v2.2.4
        with:
          name: qrcode-${{ matrix.os }}
          path: qrcode.png
          if-no-files-found: error
