name: build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: [5.0.x]

    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # tag=v3.0.0

      - name: Setup .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@9211491ffb35dd6a6657ca4f45d43dfe6e97c829 # tag=v2.0.0
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: prepare macos
        if: ${{ matrix.os == 'macos-latest' }}
        run: |
          brew install mono-libgdiplus

      - name: restore packages
        run: dotnet restore

      - name: build
        run: dotnet build --no-restore

      - name: test
        run: dotnet run --no-build

      - uses: actions/upload-artifact@82c141cc518b40d92cc801eee768e7aafc9c2fa2 # renovate: tag=v2.3.1
        with:
          name: qrcode-${{ matrix.os }}
          path: qrcode.png
          if-no-files-found: error
