name: build

on: [push]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: [5.0.x]

    steps:
      - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f # renovate: tag=v2.3.4

      - name: Setup .NET Core ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@53063334342b67eb3f5066a7ac9151683aa30b96 # renovate: tag=v1.8.1
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: restore packages
        run: dotnet restore

      - name: buld
        run: dotnet build --no-restore

      - name: test
        run: dotnet run --no-build

      - uses: actions/upload-artifact@v2
        with:
          name: qrcode-${{ matrix.os }}
          path: qrcode.png
          if-no-files-found: error
